export enum SexEnum {
  MASCULINO = "MASCULINO",
  FEMININO = "FEMININO",
}

export enum PurposeEnum {
  PERDA_PESO = "PERDA_PESO",
  GANHO_PESO = "GANHO_PESO",
  HIPERTROFIA = "HIPERTROFIA",
  MANTER_MASSA_MUSCULAR = "MANTER_MASSA_MUSCULAR",
}
